# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d40144670bf35873e0d49c6ef10c3013574be1f57aec9ff4c955982ba1d1cf40aff7974019ec2b0706ed01bca4502ca6ba0fa5761b671a583b576b8f80b6e30

test:
  secret_key_base: 55a5fa0fde2b782cae842e6528d3f88e8f5232068228ab0f46148141290d13cfd0d691920eccbc10d809b188e51a681d8b043bd37c05b876ce3ef17956cc8b17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
